name: Setup
description: Set up pnpm and install dependencies

inputs:
  node-version:
    description: Version of node to use
    default: '20'
    required: false

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: sh
      run: pnpm install
