name: CD - Docs

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub environment to use
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url}}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
