name: CD - Package

on:
  workflow_call:
    inputs:
      environment:
        description: Environment being published to
        required: true
        type: string

      build-artifact-name:
        description: Name of build artifact
        required: true
        type: string

      build-artifact-path:
        description: Path of build artifact
        required: true
        type: string

    secrets:
      NPM_AUTH_TOKEN:
        description: Authentication token for npmjs
        required: true

jobs:
  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ inputs.build-artifact-path }}

      - name: Write auth token to config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Publish package
        run: pnpm publish
