name: Release published

on:
  workflow_dispatch: # FIXME: test trigger, to be removed
  release:
    types:
      - published

env:
  PACKAGE_ENV: release
  DOCS_ENV: github-pages

jobs:
  ci-package:
    name: Package CI
    uses: ./.github/workflows/ci-package.yml

  ci-docs:
    name: Docs CI
    uses: ./.github/workflows/ci-docs.yml

  cd-package:
    name: Package CD
    needs: ci-package
    uses: ./.github/workflows/cd-package.yml
    with:
      environment: ${{ env.PACKAGE_ENV }}
      build-artifact-name: ${{ needs.ci-package.outputs.build-artifact-name }}
      build-artifact-path: ${{ needs.ci-package.outputs.build-artifact-path }}
    secrets:
      npm-auth-token: ${{ secrets.npm-auth-token }}

  cd-docs:
    name: Docs CD
    needs: ci-docs
    uses: ./.github/workflows/cd-docs.yml
    with:
      environment: ${{ env.DOCS_ENV }}
