name: Release published

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  ci-package:
    uses: './.github/workflows/ci-package.yml'

  ci-docs:
    uses: './.github/workflows/ci-docs.yml'

  cd-package:
    uses: './.github/workflows/cd-package.yml'
    needs: ci-package

  cd-docs:
    uses: './.github/workflows/cd-docs.yml'
    needs: ci-docs
