name: Release published

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  ci-package:
    uses: ./.github/workflows/ci-package.yml

  ci-docs:
    uses: ./.github/workflows/ci-docs.yml

  cd-package:
    needs: ci-package
    uses: ./.github/workflows/cd-package.yml

  cd-docs:
    needs: ci-docs
    uses: ./.github/workflows/cd-docs.yml
