name: Push to dev branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    tags-ignore:
      - '*'

jobs:
  ci-package:
    name: Package CI
    uses: ./.github/workflows/ci-package.yml
