name: Trigger - Push to main branch

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'

jobs:
  ci-package:
    name: Package CI
    uses: ./.github/workflows/ci-package.yml

  ci-docs:
    name: Docs CI
    uses: ./.github/workflows/ci-docs.yml
