name: Push to main branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'

jobs:
  ci-package:
    uses: './.github/workflows/ci-package.yml'

  ci-docs:
    uses: './.github/workflows/ci-docs.yml'
